### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by activey** [reactiverse/neo4j-client#3]
Hi,

I just wanted to build your code locally but I'm getting exceptions, lots of, but most important is this one:

```
io.vertx.codegen.GenException: type io.vertx.core.streams.WriteStream<org.neo4j.driver.Record> is not legal for use for a parameter in code generation
	at io.vertx.codegen.TypeValidator.validateParamType(TypeValidator.java:38)
	at io.vertx.codegen.ClassModel.checkParamType(ClassModel.java:576)
	at io.vertx.codegen.ClassModel.createMethod(ClassModel.java:837)
	at io.vertx.codegen.ClassModel.lambda$traverseType$13(ClassModel.java:466)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams
```
how do I proceed? ;) thanks

**Comment by activey** [comment]
Ok, it happens on vert.x 4.x line only
